//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTeamManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamTeamManagementSystemEntities : DbContext
    {
        public ExamTeamManagementSystemEntities()
            : base("name=ExamTeamManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Computer> Computers { get; set; }
        public virtual DbSet<Lab> Labs { get; set; }
        public virtual DbSet<LogisticsIssue> LogisticsIssues { get; set; }
        public virtual DbSet<StudentInformation> StudentInformations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalIssue> TechnicalIssues { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
