//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTeamManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFile
    {
        public string SN { get; set; }
        public string UniversityID { get; set; }
        public string StudentName { get; set; }
        public string Section { get; set; }
        public string Day { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Lab { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string Course { get; set; }
        public string FullDate { get; set; }
        public string Password { get; set; }
        public int Num { get; set; }
    }
}
