//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTeamManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        public string StudentFullName { get; set; }
        public string StudentID { get; set; }
        public string Course { get; set; }
        public string ExamTime { get; set; }
        public string ExamLocation { get; set; }
        public byte[] StudentPicture { get; set; }
        public string ExamDate { get; set; }
    }
}
